name: Run Python Script on Schedule

on:
  # Uncomment the schedule below to run periodically.
  # schedule:
  #  - cron: "0 * * * *"  # runs hourly; adjust as needed
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: AutoBlogScript

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets._TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate .env file
        run: |
          cat <<EOF > .env
          AI_PROVIDER=${{ secrets.AI_PROVIDER }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL=${{ secrets.OPENAI_MODEL }}
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL=${{ secrets.GEMINI_MODEL }}
          RSS_FEEDS=${{ secrets.RSS_FEEDS }}
          MAX_RSS_ITEMS=${{ secrets.MAX_RSS_ITEMS }}
          MAX_ARTICLE_AGE_DAYS=${{ secrets.MAX_RSS_ITEMS }}
          JEKYLL_CATEGORIES=${{ secrets.JEKYLL_CATEGORIES }}
          JEKYLL_TAGS=${{ secrets.JEKYLL_TAGS }}
          AUTHOR_NAME=${{ secrets.AUTHOR_NAME }}
          SITE_URL=${{ secrets.SITE_URL }}
          GITHUB_TOKEN=${{ secrets._TOKEN }}
          GITHUB_USERNAME=${{ secrets._USERNAME }}
          GITHUB_REPO=${{ secrets._REPO }}
          GITHUB_EMAIL=${{ secrets._EMAIL }}
          GITHUB_BRANCH=${{ secrets._BRANCH }}
          POSTS_PER_DAY=${{ secrets.POSTS_PER_DAY || '1' }}  # Default to 1 if not set
          EOF
        shell: bash

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets._USERNAME }}"
          git config --global user.email "${{ secrets._EMAIL }}"
          git remote set-url origin https://${{ secrets._TOKEN }}@github.com/${{ secrets._USERNAME }}/${{ secrets._REPO }}.git

      - name: Run Python Script
        env:
          # AI Provider Settings
          AI_PROVIDER: ${{ secrets.AI_PROVIDER }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: ${{ secrets.GEMINI_MODEL }}
          # RSS & Jekyll Config
          RSS_FEEDS: ${{ secrets.RSS_FEEDS }}
          MAX_RSS_ITEMS: ${{ secrets.MAX_RSS_ITEMS }}
          MAX_ARTICLE_AGE_DAYS: ${{ secrets.MAX_ARTICLE_AGE_DAYS }}
          JEKYLL_CATEGORIES: ${{ secrets.JEKYLL_CATEGORIES }}
          JEKYLL_TAGS: ${{ secrets.JEKYLL_TAGS }}
          AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
          SITE_URL: ${{ secrets.SITE_URL }}
          # GitHub push config (for pushing code to another repo)
          GITHUB_TOKEN: ${{ secrets._TOKEN }}
          GITHUB_USERNAME: ${{ secrets._USERNAME }}
          GITHUB_REPO: ${{ secrets._REPO }}
          GITHUB_EMAIL: ${{ secrets._EMAIL }}
          GITHUB_BRANCH: ${{ secrets._BRANCH }}
          # Other settings (Ads/SEO etc.) if required...
          # Environment variables loaded from .env will be used by your script
          # Additional settings can be provided here if needed.
        run: |
          python run.py