name: Run Python Script on Schedule

on:
  # schedule:
    # - cron: "0 * * * *"  # runs hourly; adjust as needed
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets._TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets._USERNAME }}"
          git config --global user.email "${{ secrets._EMAIL }}"
  
      - name: Run Python Script
        env:
          # AI Provider Settings
          AI_PROVIDER: ${{ secrets.AI_PROVIDER }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: ${{ secrets.GEMINI_MODEL }}
          # RSS & Jekyll Config
          RSS_FEEDS: ${{ secrets.RSS_FEEDS }}
          MAX_RSS_ITEMS: ${{ secrets.MAX_RSS_ITEMS }}
          MAX_ARTICLE_AGE_DAYS: ${{ secrets.MAX_ARTICLE_AGE_DAYS }}
          JEKYLL_CATEGORIES: ${{ secrets.JEKYLL_CATEGORIES }}
          JEKYLL_TAGS: ${{ secrets.JEKYLL_TAGS }}
          AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
          SITE_URL: ${{ secrets.SITE_URL }}
          # GitHub push config (for pushing code to another repo)
          GITHUB_TOKEN: ${{ secrets._TOKEN }}
          GITHUB_USERNAME: ${{ secrets._USERNAME }}
          GITHUB_REPO: ${{ secrets._REPO }}
          GITHUB_EMAIL: ${{ secrets._EMAIL }}
          GITHUB_BRANCH: ${{ secrets._BRANCH }}
          # Other settings (Ads/SEO etc.) if required...
        run: |
          # Run your main Python script, for example run.py or run_autoblog.py
          python run.py